# Generated by Django 5.2.8 on 2026-05-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0003_profile_cloud_provider_profile_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cloud_provider',
            field=models.CharField(blank=True, default='AWS', max_length=40),
        ),
    ]
